export const projects = [
  {
    title: 'Ridable Strandbeest',
    description: "Using over 500 pieces cut from  cold rolled steel, a scrap angle beam, a stainless axle, and >2000 MIG welds, I designed and built my own ridable strandbeest. Inspired by Theo Jansen with ratios adapted from Scott Burns",
      image: '/images/calsstrandbeest.gif',
      tags: ['MIG Welding', 'Solidworks CAD', 'Design Principles'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Fully Utilized Rabbit',
    description:"Designed and built a full-stack rabbit farming opperation, encompassing the breeding, birth, growth, slaughter, packaging, and sale of rabbit. The fur was also processed with my own tanning regimine. Parts of the rabbit not sold to humans was ground and sold as pet food.",
    image: '/images/rabbits.png',
    tags: ['farming', 'butchering', 'tanning'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Cockroach Breeding',
    description: "Designed and built a fully operational Blaptica Dubia cockroach farm out of my back yard. Consisting of a 700 gallon custom incubator with two racks and four bins, housing over 80,000 cockroaches (at certain points in the cycle). Diet, breeding schedules, temperature, and humidity were all derrived from experimentation. Cockroaches were packaged and sold to local pet stores as reptile and amphibian food. Thanks to my dad for funding and effort, thanks to my mum for allowing this to happen at all.",
      image: '/images/dubias.png',
      tags: ['business relations', 'carpentry'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Ledges.io',
    description: "Ledges.io is an education platform that reduces friction between students, teachers, and employers. I founded this company in 2021 and personally built the front and backend. Front end is built in JavaScript, CSS, and HTML, using the React library with the Next.js framework and redux for state management. The backend is built with MongoDB, Node.js with the Express.js framework.",
    image: '/images/ledges.png',
    tags: ['React', 'Material UI', 'MongoDB'],
    source: 'https://ledges.io',
    visit: 'https://ledges.io',
    id: 3,
  },
  {
    title: 'Print Scientific',
    description: "I have always loved building things, Print Scientific is a project that scales my ability to reach new customers, build cool shit, and manage a team. Like Ledges, I built our site and backend, for more information visit the site. Currently we specialize in high-fidelity SLA and FDM 3D printing of medical and research equipment. In the future I hope to scale this business to be able to manufacture any item with manufacturing costs as near to the price of the raw materials needed as possible.",
    image: '/images/partcollage.png',
    tags: ['CAD', 'STL', 'FDM'],
    source: 'https://printscientific.com',
    visit: 'https://printscientific.com',
    id: 3,
  },
  {
    title: 'My Body',
    description: "You only get one and it's got to last. I try to treat my body just like any other project I work on, optimizing where I can, and limiting risk wherever possible. Getting good sleep (7.5hrs/day), nutrition (minimal caloric intake for longevity purposes), exercise (biking, hiking, climbing, arm wrestling, calisthenics), stretching, brain exercises (memory, pattern recognition, problem solving), and hormonal regulation. I try to do these things everyday but if I am unable I know I can still get what I need to done.",
    image: '/images/calplanchfingertips.png',
    tags: ['sleep', 'diet', 'exercise', 'mindset'],
    source: 'https://printscientific.com',
    visit: 'https://printscientific.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];